In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings('ignore')

In [4]:
from sklearn.datasets import make_classification

In [5]:
x, y = make_classification(n_classes= 2, n_samples=1000, n_features=10, n_redundant=5, n_informative=5, random_state= 1)

In [6]:
x.shape

(1000, 10)

In [ ]:
#HyperParameter Tuning
#GridSearchCV
#RandomizedSearchCV

In [11]:
from sklearn.model_selection import GridSearchCV

In [26]:
params = {'penalty':('l1','l2','elasticnet'), 'C':[1,2,10,20,30,50]}

In [27]:
params

{'penalty': ('l1', 'l2', 'elasticnet'), 'C': [1, 2, 10, 20, 30, 50]}

In [28]:
from sklearn.linear_model import LogisticRegression

model = LogitsticRegression()

In [29]:
model = LogisticRegression()

In [30]:
model

LogisticRegression()

In [31]:
clf = GridSearchCV(model, param_grid= params, cv = 5, verbose = 2)

In [32]:
from sklearn.model_selection import train_test_split

In [33]:
X_train, X_test, Y_train, Y_test = train_test_split(x, y, random_state= 1, test_size= 0.2)

In [34]:
clf.fit(X_train, Y_train)

Fitting 5 folds for each of 18 candidates, totalling 90 fits
[CV] END ....................................C=1, penalty=l1; total time=   0.0s
[CV] END ....................................C=1, penalty=l1; total time=   0.0s
[CV] END ....................................C=1, penalty=l1; total time=   0.0s
[CV] END ....................................C=1, penalty=l1; total time=   0.0s
[CV] END ....................................C=1, penalty=l1; total time=   0.0s
[CV] END ....................................C=1, penalty=l2; total time=   0.0s
[CV] END ....................................C=1, penalty=l2; total time=   0.0s
[CV] END ....................................C=1, penalty=l2; total time=   0.0s
[CV] END ....................................C=1, penalty=l2; total time=   0.0s
[CV] END ....................................C=1, penalty=l2; total time=   0.0s
[CV] END ............................C=1, penalty=elasticnet; total time=   0.0s
[CV] END ............................C=1, penalt

GridSearchCV(cv=5, estimator=LogisticRegression(),
             param_grid={'C': [1, 2, 10, 20, 30, 50],
                         'penalty': ('l1', 'l2', 'elasticnet')},
             verbose=2)

In [35]:
clf.best_params_

{'C': 1, 'penalty': 'l2'}

In [36]:
clf.best_score_

np.float64(0.80625)

In [37]:
#Prediction two was, directly predict from best estimator
clf.best_estimator_.predict(X_test)

array([1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0,
       0, 1])

In [38]:
LogisticRegression(C= 1, penalty = '12')

LogisticRegression(C=1, penalty='12')

In [40]:
model.fit(X_train, Y_train)

LogisticRegression()

In [47]:
y_pred = model.predict(X_test)

In [45]:
model.predict_proba(X_test)[:,1]

array([0.98410215, 0.15733928, 0.29548563, 0.13456016, 0.5636631 ,
       0.08952626, 0.96607784, 0.31216935, 0.11916319, 0.96231278,
       0.07528142, 0.42568004, 0.73355127, 0.23756702, 0.59119236,
       0.6844788 , 0.95717137, 0.86931866, 0.97485839, 0.06992356,
       0.45459622, 0.96249507, 0.81921423, 0.09653146, 0.91923184,
       0.55764993, 0.14576764, 0.46233792, 0.49221641, 0.16962645,
       0.24712383, 0.77853237, 0.09474567, 0.64952045, 0.96363796,
       0.98124136, 0.99014257, 0.05049051, 0.0307142 , 0.48271716,
       0.0792749 , 0.35647405, 0.01860321, 0.43225425, 0.276453  ,
       0.17309028, 0.10617348, 0.37117309, 0.29267453, 0.04786668,
       0.12582128, 0.04210657, 0.65516811, 0.98390216, 0.60498782,
       0.10145739, 0.07451593, 0.17119768, 0.98681655, 0.97323921,
       0.99617578, 0.91084282, 0.88768326, 0.35549884, 0.94894635,
       0.19218325, 0.05533793, 0.09950113, 0.48708028, 0.73347329,
       0.24705434, 0.01975881, 0.91246865, 0.54985743, 0.98696

In [46]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [49]:
print(confusion_matrix(Y_test, y_pred))
print(accuracy_score(Y_test, y_pred))
print(classification_report(Y_test, y_pred))

[[84 10]
 [25 81]]
0.825
              precision    recall  f1-score   support

           0       0.77      0.89      0.83        94
           1       0.89      0.76      0.82       106

    accuracy                           0.82       200
   macro avg       0.83      0.83      0.82       200
weighted avg       0.83      0.82      0.82       200



In [50]:
#Randomized SearchCV
from sklearn.model_selection import RandomizedSearchCV

In [51]:
Radomized_CLF = RandomizedSearchCV(model,param_distributions= params, n_iter= 10, cv = 5) 

In [52]:
Radomized_CLF

RandomizedSearchCV(cv=5, estimator=LogisticRegression(),
                   param_distributions={'C': [1, 2, 10, 20, 30, 50],
                                        'penalty': ('l1', 'l2', 'elasticnet')})

In [53]:
Radomized_CLF.fit(X_train, Y_train)

RandomizedSearchCV(cv=5, estimator=LogisticRegression(),
                   param_distributions={'C': [1, 2, 10, 20, 30, 50],
                                        'penalty': ('l1', 'l2', 'elasticnet')})

In [55]:
Radomized_CLF.best_params_

{'penalty': 'l2', 'C': 50}

In [56]:
Radomized_CLF.best_score_

np.float64(0.80625)

In [57]:
Radomized_CLF.predict(X_test)

array([1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0,
       0, 1])