In [3]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as pl

import warnings
warnings.filterwarnings('ignore')

In [4]:
from sklearn.datasets import make_classification

In [7]:
X, Y = make_classification(n_classes= 3, n_samples= 1000, n_features= 10, n_informative= 5, n_redundant= 5, random_state= 1) 

In [9]:
X.shape

(1000, 10)

In [10]:
Y.shape

(1000,)

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size= 0.2, random_state= 1)

In [13]:
from sklearn.linear_model import LogisticRegression

In [ ]:
#OVR[One Versus Rest]

In [16]:
model = LogisticRegression(multi_class= 'ovr' , solver ='lbfgs')

In [17]:
model

LogisticRegression(multi_class='ovr')

In [18]:
model.fit(X_train, Y_train)

LogisticRegression(multi_class='ovr')

In [24]:
y_pred = model.predict(X_test)

In [25]:
from  sklearn.metrics import confusion_matrix, accuracy_score , classification_report

In [27]:
print(confusion_matrix(Y_test, y_pred))
print(f'accuracy is {accuracy_score(Y_test, y_pred)}')
print(classification_report(Y_test, y_pred))

[[46 14  0]
 [ 9 37 16]
 [17 10 51]]
accuracy is 0.67
              precision    recall  f1-score   support

           0       0.64      0.77      0.70        60
           1       0.61      0.60      0.60        62
           2       0.76      0.65      0.70        78

    accuracy                           0.67       200
   macro avg       0.67      0.67      0.67       200
weighted avg       0.68      0.67      0.67       200



In [28]:
model1= LogisticRegression(multi_class= 'multinomial', solver= 'lbfgs')

In [29]:
model1

LogisticRegression(multi_class='multinomial')

In [30]:
model1.fit(X_train, Y_train)

LogisticRegression(multi_class='multinomial')

In [31]:
model1.coef_

array([[ 0.01172519, -0.04870465,  0.22626609,  0.16110726, -0.25717652,
        -0.00144562, -0.22245679, -0.27766513, -0.02414796,  0.28798681],
       [ 0.20826758,  0.08331753, -0.42354457, -0.12688515,  0.04039496,
        -0.06112163,  0.20755203,  0.55909107, -0.19584738, -0.31971991],
       [-0.21999277, -0.03461288,  0.19727848, -0.03422211,  0.21678156,
         0.06256725,  0.01490476, -0.28142594,  0.21999534,  0.03173311]])

In [33]:
pred1 = model1.predict(X_test)

In [34]:
print(confusion_matrix(Y_test, pred1))
print(f'accuracy is {accuracy_score(Y_test, pred1)}')
print(classification_report(Y_test, pred1))

[[44 14  2]
 [11 36 15]
 [16  9 53]]
accuracy is 0.665
              precision    recall  f1-score   support

           0       0.62      0.73      0.67        60
           1       0.61      0.58      0.60        62
           2       0.76      0.68      0.72        78

    accuracy                           0.67       200
   macro avg       0.66      0.66      0.66       200
weighted avg       0.67      0.67      0.67       200



In [35]:
#ROC AUC is only for binary classification